### ISSUE TITLE
[FeatureRequest] Isometric View Render

### ISSUE THREAD

**Issue by emerysteele** [neocturne/MinedMap#28]
Prob would be a huge undertaking, but would be cool if there was an option to render an isometric view of the map.

**Comment by NeoRaider** [comment]
I assume you mean some kind of diagonal perspective? Technically speaking, MinedMap's rendering is already isometric, as there is no perspective shortening.

Adding a rotated view that is still completely flat and doesn't show the sides of blocks might be an option, but it would take considerable effort and would be much slower to render, as there is no simple region -> tile mapping anymore.

For more 3D-like modes that will actually show the sides of blocks, I don't think MinedMap is the right code base. The low-level data access library "NBT" could be reused, but all remaining code and data structures are too specialized to be of much use for anything else.

**Comment by neocturne** [comment]
As a different renderer would be pretty much a whole separate project, and the new MinedMap 2.0.0 release doesn't even use its own NBT implementation anymore, I'm closing this as out of scope.
