### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by phoenix84pl** [neocturne/MinedMap#34]
Hi!

Is it possible to write step by step guide for installation and using?

I solved at least 3 different issues during installation on Ubuntu, but I solved them with google. Others may be less lucky.

The problem which I cannot solve with google is "where is the viewer?" and "how to use it?"

I understand that I need a webserver for a viewer, but webserver needs at least a path to the viewer and example provides only: "path/to/viewer" without any explanation how to find it.

Thx for help, I hope I will be able to see my map finally.

PS. I am using ubuntu if it helps you to solve my issue.

Kamil

**Comment by neocturne** [comment]
If you're using the release builds, the viewer is a separate download that can be found on the release page: https://github.com/neocturne/MinedMap/releases/download/v2.0.1/MinedMap-2.0.1-viewer.zip. After unpacking the viewer, just point your webserver at the directory with the `index.html` and place the generated data in a directory called `data` next to `index.html`.

You're right that I should write a better how-to guide - I'll see if I can get to it soon.

I also intend to add a "standalone" mode to the generator in the future, meaning that the webserver and viewer will be built into the generator for local viewing.

**Comment by phoenix84pl** [comment]
Thx!

I found it already it was in: ~/.cargo/git/checkouts/minedmap-6e2807b44b9bd227/b32bdb4/viewer/index.html (I hope it will help others in the future)!

When it started to work I have to aprreciate your work! It is AMAZING!

I see a lot possible improvements:

1. Most important: "add text" feature (so you can name your houses or villages on the map. Programmers idea: It could take some texts from "signs" in the game if they are tagged in specific way (for example: [MM] Name) and that name could appear on the map
2. Showing altitude
3. Showing tunnels
4. What about Nether?
5. Showing open portals (with their names on signs?)

**Comment by neocturne** [comment]
All good ideas!

1. Showing signs has been a long time personal wishlist item, I've just never gotten around to implement it
2. Altitude is an interesting problem to solve. I'll have to think about possible solutions for efficient storage of the data that works well for the browser.
3. While I'm not sure what should count as a "tunnel", showing rails has been suggested before. There has been the concern that showing all underground rails might spoil the position of mine shafts. In addition, having to continue underground instead of stopping at the topmost opaque block when scanning the block data would make processing slower, but that might be okay as long as it's a configurable option.
4. See #18
5. I'll have to check whether portals only exist as a block type, or if they're also registered as a separate entity in the save data. Depending on that, the same performance issue as for underground rails may apply

**Comment by phoenix84pl** [comment]
Got it.

I understand now the problem with Nether (it is almost unsolvable like caves).

Please tell me... How block info is saved on the hard drive? All blocks are in the file or "changed" only? Cause if "changed" only then we know "what is a tunnel", cause it is different from a seed block and it is underground. The same could work for Nether.

Altitude can be generated as a "layer" so you have to choose if you prefer to see biomes or altitude (similar to "lights" layer)

With portals in case there is no special block (there should be some info, cause portals can be "open" or "close", so obsidian info is not enough) you can use obsidian frame as a reference (even underground) and give it some type of beacon on the map.

The easiest and most important would be "signs", but not all (it would be mess), but "tagged" signs, which can be recognised by your software. In case of implementig, tag should contain also some kind of formatting (like size of a text on the map).

In case you need some help (I am also a programmer, but I code mainly in PHP) you can ask for help, I cannot promise anything, but you can try :).

Thx for your work.

**Comment by neocturne** [comment]
> Please tell me... How block info is saved on the hard drive? All blocks are in the file or "changed" only? Cause if "changed" only then we know "what is a tunnel", cause it is different from a seed block and it is underground. The same could work for Nether.

For the block data, you just have a big array of the current block type at each coordinate - there is usually no way to know what block was originally generated there. For [generated structures](https://minecraft.fandom.com/wiki/Structure), there is metainformation that will give you some data on what was generated there, but I have not really looked into the details. It might be sufficient to distinguish mineshafts from user-built rail tracks, or it might be too complex to parse (in particular if the format has changed over time, which is a common issue with all of Minecraft's data structures...)

> 
> Altitude can be generated as a "layer" so you have to choose if you prefer to see biomes or altitude (similar to "lights" layer)

Ah, showing a contour map as a layer should be possible. I was thinking about showing absolute heights in the mouse hover box where X and Z coordinates are displayed, but I haven't really thought it through.

> With portals in case there is no special block (there should be some info, cause portals can be "open" or "close", so obsidian info is not enough) you can use obsidian frame as a reference (even underground) and give it some type of beacon on the map.

The air blocks inside an active portal are replaced with [portal blocks](https://minecraft.fandom.com/wiki/Nether_Portal_(block)). If the whole block data has to be scanned for such blocks, finding all portals is slower than just having a list of all portals in the save data, but as mentioned, I'm not sure whether such a list exists.

> The easiest and most important would be "signs", but not all (it would be mess), but "tagged" signs, which can be recognised by your software. In case of implementig, tag should contain also some kind of formatting (like size of a text on the map).

I agree, adding tagged signs should be easy enough.

I'm going to create a few tickets based these ideas in the next days, so there's a place to discuss the details.

**Comment by phoenix84pl** [comment]
OK, thx for the info

Now I understand how it works more less:

Conclusion:
1. Signs are not difficult and a good idea
2. Color height map as a layer I think is the easiest/best option (number on biome layer is also a good idea - I think they both could be implemented)
3. All "portal blocks" could be shown on the map as map markers (you can turn them on and off) and when clicked you get coordinates.
4. Additional layer of underground tracks can also be implemented (even if it shows shafts)

I think those are all my thoughts on the topic for now... If you need any help with some ideas, feel free to ask!

**Comment by neocturne** [comment]
I've opened separate issues for each of your suggestions now - for underground tracks, there was already an existing issue (#30). Thanks for the ideas!

**Comment by phoenix84pl** [comment]
Seen and commented already. Thx!
