### ISSUE TITLE
Sign layer

### ISSUE THREAD

**Issue by neocturne** [neocturne/MinedMap#35]
### Feature request: Add a map layer with markers for (some) signs

(suggested by multiple people, most recently by @phoenix84pl)

It should be possible to place markers on the map by putting up signs in Minecraft. Just displaying every sign will usually result in a too cluttered map, so it should be possible to specifically mark signs for display:
- Easiest solution: Only display sign texts with a given prefix (can be made configurable)
- It might also be possible to use Raw JSON text to add an attribute to make signs visible without affecting the displayed text. This should not be the only way to make signs visible, so players aren't required to deal with JSON and data commands.
- Having an additional layer with *all* signs is still an option

Open questions:
- Since Minecraft 1.20, signs have two sides. Do we want to treat both sides as separate signs, allowing do make them visible/invisible separately? Or should the MinedMap prefix make both sides visible?
- Which formatting options are important to support?
  - Formatting that can be modified in-game (dyes, glow ink sac) would be nice
  - [Formatting codes](https://minecraft.fandom.com/wiki/Formatting_codes) apparently don't work on signs, so they can be ignored
  - Additional formatting (bold, italic, ...) that can be set via [JSON](https://minecraft.fandom.com/wiki/Raw_JSON_text_format) shouldn't be too hard, but can be left for a later iteration
  - Text substitution via JSON (scoreboard, player names, translation strings, entity names) are likely too complicated or might require importing too much string data from Minecraft

**Comment by phoenix84pl** [comment]
Regarding two sides of a sign: it can be displayed as "double" also on the map

**Comment by neocturne** [comment]
I have pushed some work-in-progress code in #40

**Comment by phoenix84pl** [comment]
ok
