### ISSUE TITLE
No HTML generated

### ISSUE THREAD

**Issue by MyrddinE** [neocturne/MinedMap#46]
The images and mipmaps for the world (and night mode) are rendering, as well as the JSON, but there is no HTML file being generated to actually view the world and render the zoomable map.

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2024-02-13   6:54 PM                light
d-----        2024-02-13   6:54 PM                map
d-----        2024-02-13   6:53 PM                processed
-a----        2024-02-13   6:54 PM             12 entities.json
-a----        2024-02-13   6:54 PM           9689 info.json
```

**Comment by MyrddinE** [comment]
This is using `MinedMap-2.1.0-i686-pc-windows-msvc` on Windows 11, exporting a 1.20.1 map (with Create as the only functional mod installed that affects worldgen)

**Comment by neocturne** [comment]
The HTML is static, it can be found in a separate "viewer" download on the Github release page. The generated files need to be put in the `data` subdirectory of the unpacked viewer.

A mode that also copies the HTML into the right place with the other files could be added as part of https://github.com/neocturne/MinedMap/issues/38 (as we will need to include the HTML files in the generator for that anyways).

**Comment by MyrddinE** [comment]
Thanks, I figured that out an hour or two later. I do understand why the platform invariant files are packaged separately... but your instructions could be much clearer. I'll post a pull request with my proposal for clearer steps in the README.md.
