### ISSUE TITLE
entities.json empty with '' single quotes for --sign-* parameter

### ISSUE THREAD

**Issue by unreal4me** [neocturne/MinedMap#49]
Hi there, exccelent job!
I'm having a bit of a weird scenario. I'm running this on a server (classic jar downloaded from minecraft.net) version 1.20.4.
I'm using Windows 11, downloaded this vc_redist https://download.visualstudio.microsoft.com/download/pr/c7707d68-d6ce-4479-973e-e2a3dc4341fe/1AD7988C17663CC742B01BEF1A6DF2ED1741173009579AD50A94434E54F56073/VC_redist.x64.exe
The command line I'm using: minedmap.exe --sign-prefix '' D:\home_minecraft\world\ MinedMap-2.1.0-viewer\data\
which gets me an empty entities.json.

All works fine if you run it with double quotes as in --sign-prefix ""

I'm not using any fancy console, just the standard windows command prompt

**Comment by neocturne** [comment]
Ah, I should have known that quotes on Windows would behave differently from my Linux development machine. Using double-quotes is probably correct. I'll test a few things and update the README.
