### ISSUE TITLE
Empty regions cause mapping to fail

### ISSUE THREAD

**Issue by steffenvongrabau** [neocturne/MinedMap#52]
Using the /locate command or trading with Cartographers causes empty region files to generate. With most of them a warning appears, but some cause mapping to fail.

[minedmap.log](https://github.com/user-attachments/files/15836104/minedmap.log)
[rust_backtrace.log](https://github.com/user-attachments/files/15836133/rust_backtrace.log)

**Comment by neocturne** [comment]
Ah, I see what's going on here, I should be able to write a fix this weekend. Thanks for the report!

**Comment by steffenvongrabau** [comment]
Thanks for the quick action!
