### ISSUE TITLE
Signs - cannot make it work

### ISSUE THREAD

**Issue by phoenix84pl** [neocturne/MinedMap#55]
Hi! I am glad that you added signs as we talked before, but I cannot make it work (I have newest version 2.2.0).

I use this command and it generates map, but without signs:
minedmap ~/.minecraft/saves/L7490 ~/.cargo/git/checkouts/minedmap-6e2807b44b9bd227/b32bdb4/viewer/data --sign-prefix '[test]'

My sign says:
[test] bla1
bla2

If you need screenshots, I can make them.

What am I missing?

K.

**Comment by neocturne** [comment]
Does `viewer/data/entities.json` contain any entries? Please also provide the generated `viewer/data/info.json`.

Unrelated to your issue, but I would highly recommend against writing anything to `~/.cargo/git` - that place is for Cargo's use only. Just copy the viewer somewhere else to use it.

**Comment by phoenix84pl** [comment]
Hi!

Thx for help.

Json seems to be correct: {"signs":[{"x":-420,"y":110,"z":1241,"type":"sign","kind":"sign","material":"oak","front_text":[[{"text":"[test] bla1","color":"black"}],[{"text":"bla2","color":"black"}],[{"text":"","color":"black"}],[{"text":"","color":"black"}]]}]}

Map is still empty, what can be a reason?

I also test moving viewer to another destination.

**Comment by neocturne** [comment]
Does the layer list in the viewer show the sign layer at all? If not, it may help to clear your browser cache.

**Comment by neocturne** [comment]
Oh, I figured out what it going on. `~/.cargo/git/checkouts/minedmap-6e2807b44b9bd227/b32bdb4` is an old viewer version, b32bdb4 is just after v2.0.1. You need an up-to-date viewer - I recommend getting the version matching the generator from the Github releases page.

The version in `~/.cargo/git/checkouts` exists because you installed a Git version of MinedMap at one point, but that is only because Cargo needs to download the whole Git sources somewhere - when using a proper release from crates.io, only the generator sources are downloaded, the viewer is not supposed to be downloaded by Cargo at all.

**Comment by phoenix84pl** [comment]
seems like a solution

hmmm, how to do that if "cargo install --git 'https://github.com/neocturne/MinedMap.git'" is not enough? ;)

**Comment by phoenix84pl** [comment]
PS. No layer in the map. Just illumination is available.

**Comment by neocturne** [comment]
The viewer is supposed to be downloaded here: https://github.com/neocturne/MinedMap/releases

**Comment by neocturne** [comment]
(I do intend to integrate the viewer with the generator eventually, this is tracked in #38 - but for now, just grab the viewer zip and unpack it)

**Comment by phoenix84pl** [comment]
OK. Now it is working perfectly. Thank you for your great job.

I will not make another "issue topic", but manual is not clear enough for me... :) Your job is really appreciated, but many tickets would not appear if manual was clear :).

Thanks once again!

**Comment by phoenix84pl** [comment]
Another issue with filters :)))

What i do:
minedmap ~/.minecraft/saves/L7490 ~/Gry/Minecraft/minedMapViewer/checkouts/V7490/b32bdb4/viewer/data --sign-prefix '[test]' --sign-filter 's/\[test\]//'

What I get is this sign:
![Bildschirmfoto vom 2024-06-29 02-51-45](https://github.com/neocturne/MinedMap/assets/32969914/13de4642-f457-4f2b-805d-1517dcf9d1bc)

**Comment by neocturne** [comment]
You have mixed up `--sign-filter` and `--sign-transform`, with the latter it should work.

**Comment by phoenix84pl** [comment]
When I remove --sign-filter signs disappear from the map totally

**Comment by phoenix84pl** [comment]
OK. I made it... sorry... Is there a possibility to add --sign-transform example to readme? it would be idiot proof and will help the others :)

**Comment by phoenix84pl** [comment]
if somebody reads that in the future, this version works:

minedmap ~/.minecraft/saves/L7490 ~/Gry/Minecraft/minedMapViewer/checkouts/V7490/b32bdb4/viewer/data --sign-prefix '[Mapa]' --sign-transform 's/\[Mapa\]//'

**Comment by neocturne** [comment]
I have fixed the incorrect example in the README now.

**Comment by phoenix84pl** [comment]
Perfect!
